import type { Product, Category, Brand, Review } from "~/types";

const px = (id: number, w = 800) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}`;

export const FALLBACK_IMAGES = {
  A: px(19344605),
  B: px(17962162),
  C: px(17962161),
  D: px(14472703),
  E: px(11587603),
  F: px(12345382),
  G: px(13870347),
  H: px(39311714),
  I: px(17962164),
  J: px(17962166),
};

export const FALLBACK_CATEGORIES: Category[] = [
  { id: 1, name: "پاد یک‌بارمصرف", slug: "pods", description: "پادهای آماده مصرف با طعم‌های متنوع — بدون نیاز به کویل و سالت جدا", image: FALLBACK_IMAGES.A, count: 6 },
  { id: 2, name: "سالت نیکوتین", slug: "salts", description: "نمک نیکوتین اصل با نیکوتین ۲۰ تا ۵۰ — حس نرم و شبیه سیگار", image: FALLBACK_IMAGES.F, count: 3 },
  { id: 3, name: "مود و پاد سیستم", slug: "mods", description: "دستگاه‌های قابل شارژ با کویل قابل تعویض برای مصرف روزانه و اقتصادی", image: FALLBACK_IMAGES.C, count: 3 },
  { id: 4, name: "لوازم جانبی", slug: "gear", description: "کویل، چارجر، کیس و ابزار تمیزکاری برای نگهداری حرفه‌ای", image: FALLBACK_IMAGES.I, count: 4 },
];

export const FALLBACK_BRANDS: Brand[] = [
  { id: 1, name: "ELFBAR", slug: "elfbar", description: "پرفروش‌ترین برند پاد یک‌بارمصرف جهان", count: 2 },
  { id: 2, name: "VOZOL", slug: "vozol", description: "پادهای قدرتمند با طعم‌های خاص", count: 2 },
  { id: 3, name: "LOST MARY", slug: "lostmary", description: "طراحی مدرن و طعم‌های میوه‌ای جذاب", count: 1 },
  { id: 4, name: "IGET", slug: "iget", description: "انتخاب کلاسیک واپرهای حرفه‌ای", count: 1 },
  { id: 5, name: "AIR BAR", slug: "airbar", description: "پادهای سبک و خوش‌دست", count: 1 },
  { id: 6, name: "VAPORESSO", slug: "vaporesso", description: "مود و پاد سیستم با تکنولوژی روز", count: 3 },
  { id: 7, name: "NASTY", slug: "nasty", description: "سالت‌های مطرح مالزیایی", count: 1 },
  { id: 8, name: "VAPELAB", slug: "vapelab", description: "برند اختصاصی فروشگاه ویپ‌لب", count: 5 },
];

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 1,
    slug: "elfbar-te6000",
    name: "ELFBAR TE6000",
    tagline: "۶۰۰۰ پاف · طعم انگور یخ 🍇",
    description: "ال اف بار TE6000 با ۶۰۰۰ پاف، ۱۵ میلی‌لیتر جوخ و باتری ۶۰۰ میلی‌آمپری، محبوب‌ترین انتخاب واپرهای ایرانی است. طعم انگور یخ با سردی متعادل، کشیدنش را به یک عادت خوش‌طعم تبدیل می‌کند. دارای هولوگرام اصالت و کد استعلام.",
    specs: {
      options: JSON.stringify({
        flavors: ["انگور یخ 🍇", "هندوانه یخی 🍉", "بلوبری رازبری", "توت‌فرنگی کیوی", "سیب سبز 🍏", "لیچی"],
        nicotine: ["20", "50"],
        puffs: "۶۰۰۰ پاف",
      }),
      "مقدار جوخ": "15 ml",
      باتری: "600 mAh",
      شارژ: "Type-C",
      "نوع طعم": "میوه‌ای یخی",
    },
    price: 1150000,
    discountPrice: 990000,
    rating: 4.8,
    reviewCount: 214,
    stock: 7,
    variants: [
      { id: "v1-blue", name: "آبی متالیک", color: "آبی متالیک", hex: "#2563eb", stock: 2 },
      { id: "v1-black", name: "مشکی مات", color: "مشکی مات", hex: "#18181b", stock: 5 },
      { id: "v1-purple", name: "بنفش نئونی", color: "بنفش نئونی", hex: "#8b5cf6", stock: 0 },
    ],
    brand: "ELFBAR",
    brandSlug: "elfbar",
    category: "پاد یک‌بارمصرف",
    categorySlug: "pods",
    images: [FALLBACK_IMAGES.A, FALLBACK_IMAGES.B],
    featured: true,
    newArrival: false,
    bestSeller: true,
    createdAt: new Date(Date.now() - 120 * 86400000).toISOString(),
  },
  {
    id: 2,
    slug: "vozol-gecko-10000",
    name: "VOZOL GECKO 10000",
    tagline: "۱۰۰۰۰ پاف · نمایشگر دیجیتال ⚡",
    description: "غول جدید ووزول با ۱۰۰۰۰ پاف و نمایشگر دیجیتال که میزان جوخ و باتری را نشان می‌دهد. جریان هوا قابل تنظیم است و طعم‌ها تا آخرین پاف یکدست می‌مانند.",
    specs: {
      options: JSON.stringify({
        flavors: ["بلوبری آیس 🫐", "انبه 🥭", "هندوانه سرد", "گریپ‌فروت", "کولا یخی"],
        nicotine: ["20", "50"],
        puffs: "۱۰۰۰۰ پاف",
      }),
      "مقدار جوخ": "22 ml",
      باتری: "850 mAh",
      نمایشگر: "دیجیتال OLED",
    },
    price: 1480000,
    discountPrice: null,
    rating: 4.5,
    reviewCount: 87,
    stock: 4,
    variants: [
      { id: "v2-cyan", name: "فیروزه‌ای یخی", color: "فیروزه‌ای یخی", hex: "#06b6d4", stock: 3 },
      { id: "v2-black", name: "کربنی تیره", color: "کربنی تیره", hex: "#27272a", stock: 1 },
      { id: "v2-orange", name: "نارنجی سانست", color: "نارنجی سانست", hex: "#f97316", stock: 0 },
    ],
    brand: "VOZOL",
    brandSlug: "vozol",
    category: "پاد یک‌بارمصرف",
    categorySlug: "pods",
    images: [FALLBACK_IMAGES.B, FALLBACK_IMAGES.A],
    featured: false,
    newArrival: true,
    bestSeller: false,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 3,
    slug: "lostmary-os5000",
    name: "LOST MARY OS5000",
    tagline: "۵۰۰۰ پاف · طراحی مدرن ✨",
    description: "لاست ماری با بدنه‌ی مات و ارگونومیک، ۵۰۰۰ پاف ماندگاری دارد و طعم‌هایش بین‌المللی هستند. سایز کوچک و وزن سبکش برای همراه‌داشتن روزانه عالی است.",
    specs: {
      options: JSON.stringify({
        flavors: ["هلو 🍑", "توت‌فرنگی 🍓", "آب‌میوه قرمز", "انگور"],
        nicotine: ["20", "50"],
        puffs: "۵۰۰۰ پاف",
      }),
      "مقدار جوخ": "13 ml",
      باتری: "500 mAh",
    },
    price: 1020000,
    discountPrice: null,
    rating: 4.7,
    reviewCount: 142,
    stock: 6,
    variants: [
      { id: "v3-blue", name: "آبی کاربنی", color: "آبی کاربنی", hex: "#1d4ed8", stock: 2 },
      { id: "v3-rose", name: "رزگلد متالیک", color: "رزگلد متالیک", hex: "#fb7185", stock: 4 },
      { id: "v3-emerald", name: "سبز زمردی", color: "سبز زمردی", hex: "#10b981", stock: 0 },
    ],
    brand: "LOST MARY",
    brandSlug: "lostmary",
    category: "پاد یک‌بارمصرف",
    categorySlug: "pods",
    images: [FALLBACK_IMAGES.C, FALLBACK_IMAGES.A],
    featured: false,
    newArrival: false,
    bestSeller: true,
    createdAt: new Date(Date.now() - 200 * 86400000).toISOString(),
  },
  {
    id: 4,
    slug: "iget-xxl-5000",
    name: "IGET XXL 5000",
    tagline: "۵۰۰۰ پاف · طعم کلاسیک",
    description: "آی‌گت XXL با ۵۰۰۰ پاف و سایز بزرگ، انتخاب قدیمی‌های دنیای ویپ است. بخار حجیم و کشش باز، تجربه‌ای نزدیک به مودهای حرفه‌ای می‌دهد.",
    specs: {
      options: JSON.stringify({
        flavors: ["انگور", "بلوبری", "نعناع", "توت‌فرنگی"],
        nicotine: ["20", "50"],
        puffs: "۵۰۰۰ پاف",
      }),
      "مقدار جوخ": "12 ml",
      باتری: "550 mAh",
    },
    price: 890000,
    discountPrice: null,
    rating: 4.4,
    reviewCount: 96,
    stock: 40,
    brand: "IGET",
    brandSlug: "iget",
    category: "پاد یک‌بارمصرف",
    categorySlug: "pods",
    images: [FALLBACK_IMAGES.D, FALLBACK_IMAGES.E],
    featured: true,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date(Date.now() - 300 * 86400000).toISOString(),
  },
  {
    id: 5,
    slug: "airbar-lux-4000",
    name: "AIR BAR LUX 4000",
    tagline: "۴۰۰۰ پاف · سبک و خوش‌دست",
    description: "ایربار سبک‌ترین انتخاب روزمره است؛ ۴۰۰۰ پاف در بدنه‌ای باریک که توی جیب گم می‌شود. طعم نعناع یخی‌اش معروف است.",
    specs: {
      options: JSON.stringify({
        flavors: ["نعناع یخی ❄️", "لیمو", "انگور", "هندوانه"],
        nicotine: ["20", "50"],
        puffs: "۴۰۰۰ پاف",
      }),
      "مقدار جوخ": "10 ml",
      باتری: "450 mAh",
    },
    price: 740000,
    discountPrice: null,
    rating: 4.3,
    reviewCount: 61,
    stock: 64,
    brand: "AIR BAR",
    brandSlug: "airbar",
    category: "پاد یک‌بارمصرف",
    categorySlug: "pods",
    images: [FALLBACK_IMAGES.E, FALLBACK_IMAGES.D],
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 6,
    slug: "vapelab-puff-8000",
    name: "VAPELAB PUFF 8000",
    tagline: "۸۰۰۰ پاف · برند اختصاصی ویپ‌لب 🏷️",
    description: "پاد اختصاصی فروشگاه ویپ‌لب با ۸۰۰۰ پاف و بهترین طعم‌های پرفروش بازار، با قیمتی منصفانه‌تر و همان کیفیت اورجینال.",
    specs: {
      options: JSON.stringify({
        flavors: ["انگور یخ", "بلوبری آیس", "هندوانه سرد", "انبه"],
        nicotine: ["20", "50"],
        puffs: "۸۰۰۰ پاف",
      }),
      "مقدار جوخ": "16 ml",
      باتری: "650 mAh",
    },
    price: 1190000,
    discountPrice: 1050000,
    rating: 4.6,
    reviewCount: 38,
    stock: 28,
    brand: "VAPELAB",
    brandSlug: "vapelab",
    category: "پاد یک‌بارمصرف",
    categorySlug: "pods",
    images: [FALLBACK_IMAGES.B, FALLBACK_IMAGES.D],
    featured: false,
    newArrival: true,
    bestSeller: false,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 7,
    slug: "vapelab-salt-30",
    name: "VAPELAB SALT 30ml",
    tagline: "سالت ۳۰ میل · طعم انگور یخ",
    description: "سالت اختصاصی ویپ‌لب با ۳۰ میلی‌لیتر حجم و نیکوتین ۳۵/۵۰. ترکیب انگور و سردی نعناع، تجربه‌ای نرم و بی‌خشونت می‌سازد.",
    specs: {
      options: JSON.stringify({
        flavors: ["انگور یخ 🍇", "بلوبری 🫐", "هندوانه", "تنباکو و کارامل", "نعناع"],
        nicotine: ["35", "50"],
        salt: "نمک نیکوتین",
      }),
      حجم: "30 ml",
      "نسبت VG/PG": "50/50",
      کشور: "مالزی",
    },
    price: 385000,
    discountPrice: null,
    rating: 4.6,
    reviewCount: 173,
    stock: 80,
    brand: "VAPELAB",
    brandSlug: "vapelab",
    category: "سالت نیکوتین",
    categorySlug: "salts",
    images: [FALLBACK_IMAGES.F, FALLBACK_IMAGES.G],
    featured: false,
    newArrival: false,
    bestSeller: true,
    createdAt: new Date(Date.now() - 150 * 86400000).toISOString(),
  },
  {
    id: 8,
    slug: "elfbar-salt-30",
    name: "ELFBAR SALT 30ml",
    tagline: "سالت ۳۰ میل ال اف بار · بلوبری",
    description: "سالت اورجینال ال اف بار در بطری ۳۰ میل با طعم بلوبری شیرین و سردی ملایم. نیکوتین نرم و با کیفیت ثابت.",
    specs: {
      options: JSON.stringify({
        flavors: ["بلوبری", "انگور", "هندوانه", "توت‌فرنگی"],
        nicotine: ["35", "50"],
      }),
      حجم: "30 ml",
      کشور: "مالزی",
    },
    price: 420000,
    discountPrice: null,
    rating: 4.5,
    reviewCount: 84,
    stock: 60,
    brand: "ELFBAR",
    brandSlug: "elfbar",
    category: "سالت نیکوتین",
    categorySlug: "salts",
    images: [FALLBACK_IMAGES.G, FALLBACK_IMAGES.F],
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date(Date.now() - 150 * 86400000).toISOString(),
  },
  {
    id: 9,
    slug: "nasty-salt-30",
    name: "NASTY SALT 30ml",
    tagline: "سالت نستی · طعم ترش و شیرین 🍬",
    description: "ناستی با طعم‌های جسورانه‌اش معروف است؛ ترکیب ترش و شیرین با سردی که طرفداران خاص خودش را دارد.",
    specs: {
      options: JSON.stringify({
        flavors: ["کشنده ترش 🍬", "انگور یخ", "بلوبری"],
        nicotine: ["35", "50"],
      }),
      حجم: "30 ml",
      کشور: "مالزی",
    },
    price: 465000,
    discountPrice: null,
    rating: 4.4,
    reviewCount: 51,
    stock: 36,
    brand: "NASTY",
    brandSlug: "nasty",
    category: "سالت نیکوتین",
    categorySlug: "salts",
    images: [FALLBACK_IMAGES.F],
    featured: false,
    newArrival: true,
    bestSeller: false,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 10,
    slug: "vaporesso-luxe-xr",
    name: "VAPORESSO LUXE XR",
    tagline: "مود ۴۰ وات · کویل GTX 🔥",
    description: "لوکس XR با تراشه AXON تا ۴۰ وات توان، باتری ۱۸۰۰ میلی‌آمپری داخلی و کویل‌های GTX، یکی از بهترین مودهای جمع‌وجور برای مصرف روزانه است.",
    specs: {
      "توان خروجی": "5-40 W",
      باتری: "1800 mAh",
      "مقدار تانک": "4 ml",
      "کویل سازگار": "GTX 0.6/0.8 ohm",
      شارژ: "Type-C 2A",
    },
    price: 2450000,
    discountPrice: 2150000,
    rating: 4.8,
    reviewCount: 122,
    stock: 6,
    variants: [
      { id: "v10-black", name: "مشکی مات گلکسی", color: "مشکی مات گلکسی", hex: "#18181b", stock: 4 },
      { id: "v10-silver", name: "نقره‌ای تیتانیوم", color: "نقره‌ای تیتانیوم", hex: "#94a3b8", stock: 2 },
      { id: "v10-gold", name: "طلایی متالیک", color: "طلایی متالیک", hex: "#eab308", stock: 0 },
    ],
    brand: "VAPORESSO",
    brandSlug: "vaporesso",
    category: "مود و پاد سیستم",
    categorySlug: "mods",
    images: [FALLBACK_IMAGES.A, FALLBACK_IMAGES.D],
    featured: true,
    newArrival: false,
    bestSeller: true,
    createdAt: new Date(Date.now() - 260 * 86400000).toISOString(),
  },
  {
    id: 11,
    slug: "vaporesso-xros3",
    name: "VAPORESSO XROS 3",
    tagline: "پاد سیستم XROS · ۱۰۰۰ میلی‌آمپر",
    description: "ایکس‌راس ۳ با طراحی باریک و باتری ۱۰۰۰ میلی‌آمپری، محبوب‌ترین پاد سیستم جهان است. کویل‌های ۰.۶ و ۰.۸ اهم با طعم عالی.",
    specs: {
      باتری: "1000 mAh",
      "مقدار تانک": "2 ml",
      "کویل سازگار": "XROS 0.6/0.8/1.0 ohm",
      شارژ: "Type-C",
    },
    price: 1890000,
    discountPrice: null,
    rating: 4.7,
    reviewCount: 98,
    stock: 22,
    brand: "VAPORESSO",
    brandSlug: "vaporesso",
    category: "مود و پاد سیستم",
    categorySlug: "mods",
    images: [FALLBACK_IMAGES.B, FALLBACK_IMAGES.C],
    featured: false,
    newArrival: false,
    bestSeller: false,
    createdAt: new Date(Date.now() - 180 * 86400000).toISOString(),
  },
  {
    id: 12,
    slug: "xros-coil-pack",
    name: "XROS Coil Pack",
    tagline: "کویل اورجینال XROS — پک ۴ عددی",
    description: "کویل‌های اورجینال واپرسو برای دستگاه‌های XROS. پک ۴ عددی با مقاومت‌های ۰.۶، ۰.۸ و ۱.۰ اهم.",
    specs: {
      "مقاومت‌ها": "0.6 / 0.8 / 1.0 ohm",
      تعداد: "4 عدد",
      سازگاری: "XROS 1/2/3/4",
    },
    price: 320000,
    discountPrice: null,
    rating: 4.5,
    reviewCount: 210,
    stock: 120,
    brand: "VAPORESSO",
    brandSlug: "vaporesso",
    category: "لوازم جانبی",
    categorySlug: "gear",
    images: [FALLBACK_IMAGES.I, FALLBACK_IMAGES.G],
    featured: false,
    newArrival: false,
    bestSeller: true,
    createdAt: new Date(Date.now() - 300 * 86400000).toISOString(),
  },
];

export const FALLBACK_REVIEWS: Review[] = [
  { id: 1, author: "علی ر.", rating: 5, title: "عالی بود", body: "طعم و ماندگاری فوق‌العاده است. ارسال هم سریع بود.", createdAt: new Date().toISOString() },
  { id: 2, author: "سارا م.", rating: 5, title: "اورجینال و باکیفیت", body: "هولوگرام رو چک کردم کامل معتبر بود.", createdAt: new Date().toISOString() },
];
